Vagrant.configure("2") do |config|
    config.vm.define "serverS" do |server|
        server.vm.box = "ubuntu/bionic64"
        server.vm.hostname = "serverS"
        server.vm.network "private_network", ip: "192.168.56.110"
        
        server.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end

        server.vm.provision "shell", path: "scripts/server.sh"
    end

    config.vm.define "serverSW" do |worker|
        worker.vm.box = "ubuntu/bionic64"
        worker.vm.hostname = "serverSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end 
        worker.vm.provision "shell", path: "scripts/worker.sh"
    end 
end